### ISSUE TITLE
module 'firebase_admin.auth' has no attribute 'AuthError'

### ISSUE THREAD

**Issue by tapionx** [DoctorJohn/drf-firebase-authentication#1]
I'm using Django 3.0b1 together with Django Rest Framework and drf-firebase-authentication.

When trying to login with an incorrect Token ID i get the following error:

```
  File "/usr/local/lib/python3.7/site-packages/rest_framework/request.py", line 373, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
  File "/usr/local/lib/python3.7/site-packages/drf_firebase/authentication.py", line 38, in authenticate
    return self.authenticate_credentials(firebase_token)
  File "/usr/local/lib/python3.7/site-packages/drf_firebase/authentication.py", line 51, in authenticate_credentials
    except firebase_auth.AuthError:
rest_framework.request.WrappedAttributeError: module 'firebase_admin.auth' has no attribute 'AuthError'
```
the except used in authentication.py is wrong

**Comment by DoctorJohn** [comment]
They apparently changed the exceptions in version 3.0.0 of the firebase_admin package. Thanks for reporting.

**Comment by DoctorJohn** [comment]
I temporarily "fixed" the issue by pinning the required firebase_admin version to 2.14.0. Thats the version I excessively tested. Furthermore I created a PR that upgrades the package to the latest firebase_admin version. I need to do some testing before merging.

**Comment by DoctorJohn** [comment]
@tapionx I finished some basic testing in my own application. It works for me™. I released a new version to pypi which uses the latest version of `firebase_admin`. Feel free to report any upcoming issue.

**Comment by tapionx** [comment]
nice job!
